select top 100 'CMARCHIVESTATUS'                  as 'TableName', * from CMARCHIVESTATUS                  where cmid = 198995  --
select top 100 'CMDATA'                           as 'TableName', * from CMDATA                           where cmid = 198995  --
select top 100 'CMGUIDS'                          as 'TableName', * from CMGUIDS                          where cmid = 198995  --
select top 100 'CMOBJECTS'                        as 'TableName', * from CMOBJECTS                        where cmid = 198995  --  object details (mostly id fields)
select top 100 'CMOBJNAMES'                       as 'TableName', * from CMOBJNAMES                       where cmid = 198995  --  object names, use localeid = 96 if you're getting too many locales (or ISDEFAULT = 1)
select top 100 'CMOBJPROPS1'                      as 'TableName', * from CMOBJPROPS1                      where cmid = 198995  --  user info
select top 100 'CMOBJPROPS10'                     as 'TableName', * from CMOBJPROPS10                     where cmid = 198995  --
select top 100 'CMOBJPROPS11'                     as 'TableName', * from CMOBJPROPS11                     where cmid = 198995  --  events?
select top 100 'CMOBJPROPS13'                     as 'TableName', * from CMOBJPROPS13                     where cmid = 198995  --  parameters (related to events?  schedules?  report views?)
select top 100 'CMOBJPROPS14'                     as 'TableName', * from CMOBJPROPS14                     where cmid = 198995  --
select top 100 'CMOBJPROPS15'                     as 'TableName', * from CMOBJPROPS15                     where cmid = 198995  --
select top 100 'CMOBJPROPS16'                     as 'TableName', * from CMOBJPROPS16                     where cmid = 198995  --
select top 100 'CMOBJPROPS17'                     as 'TableName', * from CMOBJPROPS17                     where cmid = 198995  --
select top 100 'CMOBJPROPS18'                     as 'TableName', * from CMOBJPROPS18                     where cmid = 198995  --
select top 100 'CMOBJPROPS2'                      as 'TableName', * from CMOBJPROPS2                      where cmid = 198995  --  schedules, triggered schedules are type=7
select top 100 'CMOBJPROPS20'                     as 'TableName', * from CMOBJPROPS20                     where cmid = 198995  --
select top 100 'CMOBJPROPS23'                     as 'TableName', * from CMOBJPROPS23                     where cmid = 198995  --
select top 100 'CMOBJPROPS25'                     as 'TableName', * from CMOBJPROPS25                     where cmid = 198995  --
select top 100 'CMOBJPROPS26'                     as 'TableName', * from CMOBJPROPS26                     where cmid = 198995  --  schedule delivery options
select top 100 'CMOBJPROPS27'                     as 'TableName', * from CMOBJPROPS27                     where cmid = 198995  --  preferences
select top 100 'CMOBJPROPS28'                     as 'TableName', * from CMOBJPROPS28                     where cmid = 198995  --
select top 100 'CMOBJPROPS3'                      as 'TableName', * from CMOBJPROPS3                      where cmid = 198995  --  descriptions
select top 100 'CMOBJPROPS30'                     as 'TableName', * from CMOBJPROPS30                     where cmid = 198995  --
select top 100 'CMOBJPROPS31'                     as 'TableName', * from CMOBJPROPS31                     where cmid = 198995  --
select top 100 'CMOBJPROPS32'                     as 'TableName', * from CMOBJPROPS32                     where cmid = 198995  --
select top 100 'CMOBJPROPS33'                     as 'TableName', * from CMOBJPROPS33                     where cmid = 198995  --  user names
select top 100 'CMOBJPROPS34'                     as 'TableName', * from CMOBJPROPS34                     where cmid = 198995  --
select top 100 'CMOBJPROPS36'                     as 'TableName', * from CMOBJPROPS36                     where cmid = 198995  --
select top 100 'CMOBJPROPS37'                     as 'TableName', * from CMOBJPROPS37                     where cmid = 198995  --
select top 100 'CMOBJPROPS38'                     as 'TableName', * from CMOBJPROPS38                     where cmid = 198995  --
select top 100 'CMOBJPROPS39'                     as 'TableName', * from CMOBJPROPS39                     where cmid = 198995  --
select top 100 'CMOBJPROPS4'                      as 'TableName', * from CMOBJPROPS4                      where cmid = 198995  --
select top 100 'CMOBJPROPS44'                     as 'TableName', * from CMOBJPROPS44                     where cmid = 198995  --
select top 100 'CMOBJPROPS45'                     as 'TableName', * from CMOBJPROPS45                     where cmid = 198995  --
select top 100 'CMOBJPROPS48'                     as 'TableName', * from CMOBJPROPS48                     where cmid = 198995  --
select top 100 'CMOBJPROPS49'                     as 'TableName', * from CMOBJPROPS49                     where cmid = 198995  --  file system locations -- admin | Configuration | Dispatchers and Services | Define File System Locations
select top 100 'CMOBJPROPS5'                      as 'TableName', * from CMOBJPROPS5                      where cmid = 198995  --  run history details
select top 100 'CMOBJPROPS50'                     as 'TableName', * from CMOBJPROPS50                     where cmid = 198995  --
select top 100 'CMOBJPROPS51'                     as 'TableName', * from CMOBJPROPS51                     where cmid = 198995  --  trigger infor for schedules, use which viewer (compatible or interactive)
select top 100 'CMOBJPROPS52'                     as 'TableName', * from CMOBJPROPS52                     where cmid = 198995  --  dataSourceConnection
select top 100 'CMOBJPROPS53'                     as 'TableName', * from CMOBJPROPS53                     where cmid = 198995  --
select top 100 'CMOBJPROPS54'                     as 'TableName', * from CMOBJPROPS54                     where cmid = 198995  --
select top 100 'CMOBJPROPS55'                     as 'TableName', * from CMOBJPROPS55                     where cmid = 198995  --
select top 100 'CMOBJPROPS58'                     as 'TableName', * from CMOBJPROPS58                     where cmid = 198995  --
select top 100 'CMOBJPROPS59'                     as 'TableName', * from CMOBJPROPS59                     where cmid = 198995  --
select top 100 'CMOBJPROPS6'                      as 'TableName', * from CMOBJPROPS6                      where cmid = 198995  --  URLs and shortcuts
select top 100 'CMOBJPROPS61'                     as 'TableName', * from CMOBJPROPS61                     where cmid = 198995  --  related to bursting
select top 100 'CMOBJPROPS62'                     as 'TableName', * from CMOBJPROPS62                     where cmid = 198995  --
select top 100 'CMOBJPROPS65'                     as 'TableName', * from CMOBJPROPS65                     where cmid = 198995  --  related to bursting
select top 100 'CMOBJPROPS66'                     as 'TableName', * from CMOBJPROPS66                     where cmid = 198995  --
select top 100 'CMOBJPROPS67'                     as 'TableName', * from CMOBJPROPS67                     where cmid = 198995  --  configuration items for performance tuning
select top 100 'CMOBJPROPS7'                      as 'TableName', * from CMOBJPROPS7                      where cmid = 198995  --  report specs and ?
select top 100 'CMOBJPROPS71'                     as 'TableName', * from CMOBJPROPS71                     where cmid = 198995  --
select top 100 'CMOBJPROPS76'                     as 'TableName', * from CMOBJPROPS76                     where cmid = 198995  --
select top 100 'CMOBJPROPS77'                     as 'TableName', * from CMOBJPROPS77                     where cmid = 198995  --
select top 100 'CMOBJPROPS79'                     as 'TableName', * from CMOBJPROPS79                     where cmid = 198995  --  portalSkins (skins, themes) -- edit using Theme Designer
select top 100 'CMOBJPROPS80'                     as 'TableName', * from CMOBJPROPS80                     where cmid = 198995  --
select top 100 'CMOBJPROPS82'                     as 'TableName', * from CMOBJPROPS82                     where cmid = 198995  --
select top 100 'CMOBJPROPS83'                     as 'TableName', * from CMOBJPROPS83                     where cmid = 198995  --
select top 100 'CMOBJPROPS84'                     as 'TableName', * from CMOBJPROPS84                     where cmid = 198995  --
select top 100 'CMOBJPROPS85'                     as 'TableName', * from CMOBJPROPS85                     where cmid = 198995  --
select top 100 'CMOBJPROPS86'                     as 'TableName', * from CMOBJPROPS86                     where cmid = 198995  --  data module definitions?  Encoded how?
select top 100 'CMOBJPROPS87'                     as 'TableName', * from CMOBJPROPS87                     where cmid = 198995  --
select top 100 'CMOBJPROPS88'                     as 'TableName', * from CMOBJPROPS88                     where cmid = 198995  --
select top 100 'CMOBJPROPS9'                      as 'TableName', * from CMOBJPROPS9                      where cmid = 198995  --
select top 100 'CMPOLICIES'                       as 'TableName', * from CMPOLICIES                       where cmid = 198995  --  permissions?  (Data is stored in a "image".  Use a hex to ascii converter.)
select top 100 'CMREFNOORD1'                      as 'TableName', * from CMREFNOORD1                      where cmid = 198995  --  report view to report relationships - and...?
select top 100 'CMREFNOORD2'                      as 'TableName', * from CMREFNOORD2                      where cmid = 198995  --
select top 100 'CMREFORD1'                        as 'TableName', * from CMREFORD1                        where cmid = 198995  --
select top 100 'CMREFORD2'                        as 'TableName', * from CMREFORD2                        where cmid = 198995  --
select top 100 'CMSTOREIDS'                       as 'TableName', * from CMSTOREIDS                       where cmid = 198995  --
select top 100 'CMVIEWED'                         as 'TableName', * from CMVIEWED                         where cmid = 198995  --
select top 100 'CMREFNOORD1'                      as 'TableName', * from CMREFNOORD1                   where refcmid = 198995  --  report view to report relationships - and...?
select top 100 'CMREFNOORD2'                      as 'TableName', * from CMREFNOORD2                   where refcmid = 198995  --
select top 100 'CMREFORD1'                        as 'TableName', * from CMREFORD1                     where refcmid = 198995  --
select top 100 'CMREFORD2'                        as 'TableName', * from CMREFORD2                     where refcmid = 198995  --

